baseurl = "https://github.com/"
languageCode = "zh-rcn"
title = "Usher Baby"
theme = "HugoMDL"
MetaDataFormat = "yaml"
[permalinks]
	page = "/:title/"
	about = "/:filename/"
[params]
    author = "Usher Baby"
    avatar = "/images/avatar.png"
    background = "/images/background.jpg"
    description = "A place to publish my incomprehensible ramblings" #meta description
    image = "/images/avatar-192x210.png" #for frontpage profile card
    website = "https://github.com/ThePacific"
    email = "io.2016@outlook.com"
    twitter = "https://twitter.com/firstname_lastname"
    github = "https://github.com/firstname_lastname/"
    linkedin = "https://linkedin.com/in/firstname_lastname/"
    facebook = "https://facebook.com/firstname_lastname/"
    copyrightyear = "2016"
    frontpageposts = 6 #number of post cards to display on frontpage
    
